name: Push container
description: ""

inputs:
  image-id:
    description: "Image ID"
    required: true
  destination-hosts:
    description: "Where to upload the artifact to - if only local is desired just use \"localhost:5000\" - trailing slash is not allowed. Must be a text with a yaml array of hosts"
    required: true
    default: |
      - ghcr.io
  destination-image-names:
    description: "Must be a text with a yaml array of hosts"
    required: true
    default: |
      - ${{ github.repository }}
  auto-tagging:
    description: ""
    required: true
    default: "TAGS_AS_RELEASE"
  destination-tags:
    description: "Must be a text with a yaml array of hosts."
    required: true
    default: |
      []

outputs:
  digest:
    description: Image digest for usage in helm charts or other deployments where it is desired to lock the version to this build

  images-pushed:
    description: Full list (as yaml array) of image names pushed

runs:
  using: node20
  main: index.js
